/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.AbaBankingRecordAllOf;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.BaseAuditRecordWithUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AbaBankingRecord
 */
public class AbaBankingRecordTest {
    private final AbaBankingRecord model = new AbaBankingRecord();

    /**
     * Model tests for AbaBankingRecord
     */
    @Test
    public void testAbaBankingRecord() {
        // TODO: test AbaBankingRecord
    }

    /**
     * Test the property 'ababankingid'
     */
    @Test
    public void ababankingidTest() {
        // TODO: test ababankingid
    }

    /**
     * Test the property 'routingnumber'
     */
    @Test
    public void routingnumberTest() {
        // TODO: test routingnumber
    }

    /**
     * Test the property 'telegraphicname'
     */
    @Test
    public void telegraphicnameTest() {
        // TODO: test telegraphicname
    }

    /**
     * Test the property 'customername'
     */
    @Test
    public void customernameTest() {
        // TODO: test customername
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'statecode'
     */
    @Test
    public void statecodeTest() {
        // TODO: test statecode
    }

    /**
     * Test the property 'zipcode'
     */
    @Test
    public void zipcodeTest() {
        // TODO: test zipcode
    }

    /**
     * Test the property 'createduser'
     */
    @Test
    public void createduserTest() {
        // TODO: test createduser
    }

    /**
     * Test the property 'createddate'
     */
    @Test
    public void createddateTest() {
        // TODO: test createddate
    }

    /**
     * Test the property 'statusid'
     */
    @Test
    public void statusidTest() {
        // TODO: test statusid
    }

    /**
     * Test the property 'registeredapp'
     */
    @Test
    public void registeredappTest() {
        // TODO: test registeredapp
    }

}
