/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AreaCodeAllOf
 */
public class AreaCodeAllOfTest {
    private final AreaCodeAllOf model = new AreaCodeAllOf();

    /**
     * Model tests for AreaCodeAllOf
     */
    @Test
    public void testAreaCodeAllOf() {
        // TODO: test AreaCodeAllOf
    }

    /**
     * Test the property 'areacodeid'
     */
    @Test
    public void areacodeidTest() {
        // TODO: test areacodeid
    }

    /**
     * Test the property 'areacodevalue'
     */
    @Test
    public void areacodevalueTest() {
        // TODO: test areacodevalue
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'statecode'
     */
    @Test
    public void statecodeTest() {
        // TODO: test statecode
    }

}
