/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BaseAuditRecord
 */
public class BaseAuditRecordTest {
    private final BaseAuditRecord model = new BaseAuditRecord();

    /**
     * Model tests for BaseAuditRecord
     */
    @Test
    public void testBaseAuditRecord() {
        // TODO: test BaseAuditRecord
    }

    /**
     * Test the property 'createddate'
     */
    @Test
    public void createddateTest() {
        // TODO: test createddate
    }

    /**
     * Test the property 'statusid'
     */
    @Test
    public void statusidTest() {
        // TODO: test statusid
    }

    /**
     * Test the property 'registeredapp'
     */
    @Test
    public void registeredappTest() {
        // TODO: test registeredapp
    }

}
