/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.BaseAuditRecordWithUser;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.LastNameAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LastName
 */
public class LastNameTest {
    private final LastName model = new LastName();

    /**
     * Model tests for LastName
     */
    @Test
    public void testLastName() {
        // TODO: test LastName
    }

    /**
     * Test the property 'lastnameid'
     */
    @Test
    public void lastnameidTest() {
        // TODO: test lastnameid
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'createduser'
     */
    @Test
    public void createduserTest() {
        // TODO: test createduser
    }

    /**
     * Test the property 'createddate'
     */
    @Test
    public void createddateTest() {
        // TODO: test createddate
    }

    /**
     * Test the property 'statusid'
     */
    @Test
    public void statusidTest() {
        // TODO: test statusid
    }

    /**
     * Test the property 'registeredapp'
     */
    @Test
    public void registeredappTest() {
        // TODO: test registeredapp
    }

}
