/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.BaseAuditRecordWithUser;
import io.connectedhealth.idaas.datasynthesis.javaclient.model.UpcCodeAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpcCode
 */
public class UpcCodeTest {
    private final UpcCode model = new UpcCode();

    /**
     * Model tests for UpcCode
     */
    @Test
    public void testUpcCode() {
        // TODO: test UpcCode
    }

    /**
     * Test the property 'upccodeid'
     */
    @Test
    public void upccodeidTest() {
        // TODO: test upccodeid
    }

    /**
     * Test the property 'upccodename'
     */
    @Test
    public void upccodenameTest() {
        // TODO: test upccodename
    }

    /**
     * Test the property 'upcproductname'
     */
    @Test
    public void upcproductnameTest() {
        // TODO: test upcproductname
    }

    /**
     * Test the property 'createduser'
     */
    @Test
    public void createduserTest() {
        // TODO: test createduser
    }

    /**
     * Test the property 'createddate'
     */
    @Test
    public void createddateTest() {
        // TODO: test createddate
    }

    /**
     * Test the property 'statusid'
     */
    @Test
    public void statusidTest() {
        // TODO: test statusid
    }

    /**
     * Test the property 'registeredapp'
     */
    @Test
    public void registeredappTest() {
        // TODO: test registeredapp
    }

}
