/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpcCodeAllOf
 */
public class UpcCodeAllOfTest {
    private final UpcCodeAllOf model = new UpcCodeAllOf();

    /**
     * Model tests for UpcCodeAllOf
     */
    @Test
    public void testUpcCodeAllOf() {
        // TODO: test UpcCodeAllOf
    }

    /**
     * Test the property 'upccodeid'
     */
    @Test
    public void upccodeidTest() {
        // TODO: test upccodeid
    }

    /**
     * Test the property 'upccodename'
     */
    @Test
    public void upccodenameTest() {
        // TODO: test upccodename
    }

    /**
     * Test the property 'upcproductname'
     */
    @Test
    public void upcproductnameTest() {
        // TODO: test upcproductname
    }

}
