/*
 * Query API
 * A list of get API calls that allows for pulling data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.connectedhealth.idaas.datasynthesis.javaclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ZipCodeUSAllOf
 */
public class ZipCodeUSAllOfTest {
    private final ZipCodeUSAllOf model = new ZipCodeUSAllOf();

    /**
     * Model tests for ZipCodeUSAllOf
     */
    @Test
    public void testZipCodeUSAllOf() {
        // TODO: test ZipCodeUSAllOf
    }

    /**
     * Test the property 'zipcodeid'
     */
    @Test
    public void zipcodeidTest() {
        // TODO: test zipcodeid
    }

    /**
     * Test the property 'zipcode'
     */
    @Test
    public void zipcodeTest() {
        // TODO: test zipcode
    }

    /**
     * Test the property 'zipcodetype'
     */
    @Test
    public void zipcodetypeTest() {
        // TODO: test zipcodetype
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'statecode'
     */
    @Test
    public void statecodeTest() {
        // TODO: test statecode
    }

    /**
     * Test the property 'lattitude'
     */
    @Test
    public void lattitudeTest() {
        // TODO: test lattitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'lctn'
     */
    @Test
    public void lctnTest() {
        // TODO: test lctn
    }

}
