organization: 'herophilus'
# The organization ID of a Redocly Workflows organization.
# Used for easier integration with the API registry and hosted Reference docs,
# not required for local OpenAPI CLI usage.
apis:
# A collection of objects, each representing one API.
# An API should be defined by a name, an optional version,
# and the path to the root OpenAPI document.
# Additionally, each API can have its own lint and features.openapi
# sections for fine-grained control.
# Example:
  main:
    root: ./openapi/openapi.yaml
    lint:
      rules:
        example-rule: warn
lint:
  extends:
    -  minimal
    # https://redocly.com/docs/cli/resources/built-in-rules/
    # Will want to implement recommended rules with some modification eventually
    # -  recommended
  rules:
    operation-2xx-response: warn
    # I dont fully understand this but I get errors when using allOf + examples
    # This issue remains open https://github.com/Redocly/openapi-cli/issues/552
    no-invalid-media-type-examples:
      disallowAdditionalProperties: false
  
# Global configuration for the lint command.

#features.mockServer:
# Configuration for the optional mock server feature in the API registry.
# Available in Pro and Enterprise plans only.

#region: eu
# Configuration for optional AWS region selection when logging into Redocly services.

#resolve:
# Configuration for resolving external links in your definition that are not publicly accessible.
# Not required for Redocly API registry links.

#features.openapi:
# The API reference docs options, including theme options.

#registry:
# The API registry options

# future products may be configured by extending this file