select
platform_datastructurestodataattributes.platformdatastructurestodataattributesid,
platform_datastructurestodataattributes.platformdatastructuresid,
platform_datastructures.datastructurename,
platform_datastructurestodataattributes.platformdataattributesid,
platform_dataattributes.dataattributename,
platform_dataattributes.platformtablename
from platform_datastructurestodataattributes, platform_dataattributes,
platform_datastructures
where
platform_datastructurestodataattributes.platformdataattributesid =
platform_dataattributes.platformdataattributesid
and
platform_datastructurestodataattributes.platformdatastructuresid =
platform_datastructures.platformdatastructuresid
and
platform_datastructurestodataattributes.statusid =1
order by
platform_datastructurestodataattributes.platformdatastructuresid