create or replace database DATASYNTHESIS
	data_retention_time_in_days = 1;

create or replace table PUBLIC.DATAMODEL_DATATABLES
(
	TABLENAME VARCHAR(64) not null
		constraint PK_DATAMODEL_DATATABLES
			primary key,
	TABLEINFORMATION VARCHAR(249),
	STATUSID NUMBER default 1,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP()
);

create or replace table PUBLIC.REFDATA_STATUS
(
	STATUSID NUMBER identity
		constraint PK_REFDATASTATUS
			primary key,
	STATUSDESCRIPTION VARCHAR(45) not null,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20)
);

create or replace table PUBLIC.AUDITING_DATAPLATFORM
(
	DATAPLATFORMID NUMBER identity
		primary key,
	DATAPROCESSINGDATE TIMESTAMPNTZ,
	CREATEDBYUSER VARCHAR(20),
	ORGANIZATON VARCHAR(38),
	APPLICATION VARCHAR(38),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_DATAPLATFORM_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	RECCOUNT NUMBER,
	COMPONENT VARCHAR(20),
	ACTIONNAME VARCHAR(20),
	DURATIONTORUN NUMBER,
	ACTIVITYDETAIL VARCHAR(75)
);

create or replace table PUBLIC.AUDITING_DATAREQUEST
(
	DATAREQUESTID NUMBER identity
		constraint PK_AUDITING_DATAREQUEST
			primary key,
	DATAREQUESTDATE TIMESTAMPNTZ,
	CREATEDBYUSER VARCHAR(20),
	ORGANIZATON VARCHAR(38),
	APPLICATION VARCHAR(38),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_DATAREQUEST_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	RECCOUNT NUMBER,
	RECORDDATAREQUEST VARCHAR(400)
);

create or replace table PUBLIC.PLATFORM_RULESETS
(
	RULEID NUMBER identity
		constraint PK_PLATFORM_RULESETS
			primary key,
	RULENAME VARCHAR(65),
	CREATEDUSER VARCHAR(20),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_RULESETS_STATUS
			references PUBLIC.REFDATA_STATUS,
	EXPIRATIONDATE TIMESTAMPNTZ
);

create or replace table PUBLIC.REFDATA_ADDRESSFORMATTYPE
(
	ADDRESSFORMATTYPEID NUMBER identity
		constraint PK_REFDATA_ADDRESSFORMATTYPE
			primary key,
	ADDRESSFORMATTYPEDESC VARCHAR(35),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_ADDRESSFORMATTYPE_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_COUNTRIES
(
	COUNTRYID NUMBER identity
		constraint PK_REFDATA_COUNTRIES
			primary key,
	IDD VARCHAR(5),
	COUNTRYNAME VARCHAR(59),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_COUNTRIES_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_INDUSTRYSTD
(
	INDUSTRYSTD VARCHAR(6) not null
		constraint PK_REFDATA_INDUSTRYSTD
			primary key,
	INDUSTRYSTDDESC VARCHAR(30),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_INDUSTRYSTD_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_OPERATIONTYPE
(
	OPERATIONTYPEID VARCHAR(7) not null
		constraint PK_OPERATION_TYPE
			primary key,
	OPERATIONTYPENAME VARCHAR(60),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_OPERATIONTYPE_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_PLATFORMPARAMS
(
	PLATFORMPARAMSID NUMBER identity
		constraint PK_REFDATA_PLATFORMPARAMS
			primary key,
	PLATFORMPARAMVALUES VARCHAR(35),
	PLATFORMPARAMDESC VARCHAR(70),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_PLATFORMPARAMS_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_SENSITIVITYFLAG
(
	SENSITIVEFLAGID NUMBER identity
		constraint PK_REFDATA_SENSITITYFLAG
			primary key,
	SENSITIVEFLAGDESC VARCHAR(30),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_SENSITIVITYFLAG_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_CODESET
(
	CODESETSID NUMBER identity
		constraint PK_REFDATA_CODESET
			primary key,
	CODESETNAME VARCHAR(50),
	INDUSTRYSTD VARCHAR(6)
		constraint FK_REFDATA_CODESET_INDUSTRYSTD
			references PUBLIC.REFDATA_INDUSTRYSTD,
	STATUSID NUMBER default 1
		constraint FK_REFDATA_CODESETS_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20),
	CODESETGUID VARCHAR(38),
	FIELDMAPPING VARCHAR(20),
	SENSITIVITYFLAGID NUMBER
		constraint FK_REFDATA_CODESET_SENSITIVITYFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG
);

create or replace table PUBLIC.REFDATA_CODESETSTRUCTURES
(
	CODESETSTRUCTURESID NUMBER identity
		constraint PK_REFDATA_CODESETSTRUCTURES
			primary key,
	CODESETSTRUCTURENAME VARCHAR(50),
	INDUSTRYSTD VARCHAR(6)
		constraint FK_REFDATA_CODESETSTRUCTURES_INDUSTRYSTD
			references PUBLIC.REFDATA_INDUSTRYSTD,
	STATUSID NUMBER default 1
		constraint FK_REFDATA_CODESETSTRUCTURES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20),
	CODESETSTRUCTUREGUID VARCHAR(38),
	FIELD1VALUE VARCHAR(75),
	FIELD2VALUE VARCHAR(75),
	FIELD3VALUE VARCHAR(75),
	FIELD4VALUE VARCHAR(75),
	FIELD5VALUE VARCHAR(75),
	FIELD6VALUE VARCHAR(75),
	FIELD7VALUE VARCHAR(75),
	FIELD8VALUE VARCHAR(75),
	FIELD9VALUE VARCHAR(75),
	SENSITIVITYFLAGID NUMBER
		constraint FK_REFDATA_CODESETSTRUCTURES_SENSITIVITYFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG,
	CODESETSID NUMBER
		constraint FK_REFDATA_CODESETSTRUCTURES_CODESETS
			references PUBLIC.REFDATA_CODESET
);

create or replace table PUBLIC.REFDATA_TIMEZONES
(
	TIMEZONEVALUE VARCHAR(3) not null
		constraint PK_REFDATA_TIMEZONES
			primary key,
	TIMEZONEDESC VARCHAR(25),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_TIMEZONES_STATUS
			references PUBLIC.REFDATA_STATUS
);

create or replace table PUBLIC.REFDATA_USSTATES
(
	STATEID VARCHAR(2) not null
		constraint PK_REFDATA_USSTATES
			primary key,
	STATEDESCRIPTION VARCHAR(65),
	LATTITUDE VARCHAR(12),
	LONGITUDE VARCHAR(12),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_USSTATES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20)
);

create or replace table PUBLIC.REFDATA_LEGALENTITY
(
	LEGALENTITYGUID VARCHAR(38) not null
		constraint PK_REFDATA_LEGALENTITY
			primary key,
	LOCATIONNAME VARCHAR(50),
	ADDRESS VARCHAR(75),
	CITY VARCHAR(60),
	STATEID VARCHAR(2)
		constraint FK_REFDATA_LOCATION_STATES
			references PUBLIC.REFDATA_USSTATES,
	ZIPCODE VARCHAR(12),
	CREATEDUSER VARCHAR(20),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_LOCATION_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP() not null,
	LOCATIONURL VARCHAR(99),
	LOCATIONPHONE VARCHAR(12)
);

create or replace table PUBLIC.REFDATA_ORGANIZATION
(
	ORGANIZATIONGUID VARCHAR(38) not null
		constraint PK_REFDATA_ORGANIZATION
			primary key,
	ORGANIZATIONINTERNALCODE VARCHAR(10),
	ORGANIZATIONINTERNALID VARCHAR(10),
	ORGANIZATIONNAME VARCHAR(50),
	ADDRESS VARCHAR(75),
	CITY VARCHAR(60),
	STATEID VARCHAR(2)
		constraint FK_REFDATA_ORGANIZATION_STATES
			references PUBLIC.REFDATA_USSTATES,
	ZIPCODE VARCHAR(12),
	CREATEDUSER VARCHAR(20),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_ORGANIZATION_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP() not null,
	LEGALENTITYGUID VARCHAR(38)
		constraint FK_REFDATA_ORGANIZATION_LEGALENTITY
			references PUBLIC.REFDATA_LEGALENTITY
);

create or replace table PUBLIC.REFDATA_VENDOR
(
	VENDORID NUMBER identity
		constraint PK_REFDATA_VENDOR
			primary key,
	VENDORNAME VARCHAR(50),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_VENDORS_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	VENDORGUID VARCHAR(38)
);

create or replace table PUBLIC.REFDATA_APPLICATION
(
	APPGUID VARCHAR(38) not null
		constraint PK_REFDATA_APPLICATION
			primary key,
	APPLICATIONCUSTOMCODE VARCHAR(15),
	APPLICATIONDESC VARCHAR(50),
	CREATEDUSER VARCHAR(20),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_APPLICATION_STATUS
			references PUBLIC.REFDATA_STATUS,
	VENDORID NUMBER
		constraint FK_REFDATA_APPLICATION_VENDORS
			references PUBLIC.REFDATA_VENDOR
);

create or replace table PUBLIC.DATABUILT_ADDRESS
(
	COMPLETEADDRESSID NUMBER identity
		constraint PK_DATABUILT_ADDRESS
			primary key,
	ADDRESS1 VARCHAR(99),
	CITY VARCHAR(70),
	STATEID VARCHAR(2),
	ZIPCODE VARCHAR(10),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_ADDRESS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_ADDRESS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_BANKACCOUNT
(
	DATABUILTBANKACCOUNTSID NUMBER identity
		constraint PK_DATABUILT_BANKACCOUNT
			primary key,
	BANKACCOUNTNUMBER VARCHAR(12),
	BANKACCOUNTNAME VARCHAR(75),
	BANKROUTINGID VARCHAR(9),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_BANKACCOUNTS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_BANKACCOUNT_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_CORPORATIONS
(
	DATABUILTCORPORATIONID NUMBER identity
		constraint PK_DATABUILT_CORPORATIONS
			primary key,
	CORPORATIONNAME VARCHAR(99),
	ADDRESS1 VARCHAR(99),
	CITY VARCHAR(70),
	STATEID VARCHAR(2),
	ZIPCODE VARCHAR(10),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_CORPORATIONS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_CORPORATIONS_RESITEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_NAMES
(
	DATABUILTNAMESID NUMBER identity
		constraint PK_DATABUILT_NAMES
			primary key,
	COMPLETENAME VARCHAR(100),
	GENDER VARCHAR(1),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_COMPLETENAMES_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_NAMES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_PERSONDEMOGRAPHICS
(
	PERSONDEMOGRAPHICSID NUMBER identity
		constraint PK_DATABUILT_PERSONDEMOGRAPHICS
			primary key,
	GENDER VARCHAR(1),
	DLN VARCHAR(25),
	DLNSTATE VARCHAR(2),
	SSN VARCHAR(11),
	DOBVALUE VARCHAR(12),
	DOBDATE DATE,
	AGE NUMBER,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_PERSONDEMOGRAPHICS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_PERSONDEMOGRAPHICS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_PHONENUMBERS
(
	DATABUILTPHONENUMBERSID NUMBER identity
		constraint PK_DATABUILT_PHONENUMBERS
			primary key,
	AREACODE VARCHAR(3),
	PHONENUMBER VARCHAR(8),
	COMPLETEPHONENUMBER VARCHAR(14),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_PHONENUMBERS_STATUS
			references PUBLIC.REFDATA_STATUS
		constraint IDX_DATABUILT_PHONENUMBERS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_PHONENUMBERS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATABUILT_PRODUCTS
(
	DATABUILTPRODUCTSID NUMBER identity
		constraint PK_DATABUILT_PRODUCTS
			primary key,
	PRODUCTID VARCHAR(20),
	PRODUCTNAME VARCHAR(99),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATABUILT_PRODUCTS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATABUILT_PRODUCTS_REGSITEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_ABABANKING
(
	ABABANKINGID NUMBER identity
		constraint PK_DATAEXISTING_ABABANKING
			primary key,
	ROUTINGNUMBER VARCHAR(9),
	TELEGRAPHICNAME VARCHAR(20),
	CUSTOMERNAME VARCHAR(36),
	CITY VARCHAR(20),
	STATE VARCHAR(2),
	ZIPCODE VARCHAR(5),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_ABABANKING_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_ABABANKING_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_AREACODE
(
	AREACODEID NUMBER identity
		constraint PK_DATAEXISTING_AREACODE
			primary key,
	AREACODEVALUE VARCHAR(3) not null,
	TIMEZONE VARCHAR(3)
		constraint FK_DATAEXISTING_AREACODE_TIMEZONES
			references PUBLIC.REFDATA_TIMEZONES,
	STATECODE VARCHAR(2)
		constraint FK_DATAEXISTING_AREACODE_USSTATES
			references PUBLIC.REFDATA_USSTATES,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_AREACODE_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_AREACODE_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_AREACODEINTL
(
	IDDCODE VARCHAR(5) not null
		constraint PK_DATAEXISTING_AREACODEINTL
			primary key,
	COUNTRYID NUMBER
		constraint FK_DATAEXISTING_AREACODEINTL_COUNTRIES
			references PUBLIC.REFDATA_COUNTRIES,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_AREACODEINTL_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_AREACODEINTL_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_COMPANIES
(
	COMPANIESID NUMBER identity
		constraint PK_DATAEXISTING_COMPANIES
			primary key,
	COMPANYNAME VARCHAR(79),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_COMPANIES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_COMPANIES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_NAMEFIRST
(
	FIRSTNAMEID NUMBER identity
		constraint PK_DATAEXISTING_NAMEFIRST
			primary key,
	FIRSTNAME VARCHAR(39),
	GENDER VARCHAR(1),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_NAMEFIRST_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_NAMEFIRST_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_NAMELAST
(
	LASTNAMEID NUMBER identity
		constraint PK_DATAEXISTING_NAMELAST
			primary key,
	LASTNAME VARCHAR(69),
	STATUSID NUMBER default 1 not null
		constraint FK_DATAEXISTING_NAMELAST_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_NAMELAST_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_UPCCODES
(
	UPCCODEID NUMBER identity
		constraint PK_DATAEXISTING_UPCCODES
			primary key,
	UPCCODENAME VARCHAR(15),
	UPCPRODUCTNAME VARCHAR(150),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_UPCCODES_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_UPCCODES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_ZIPCODEINTL
(
	ZIPCODEINTNLID NUMBER identity
		constraint PK_DATAEXISTING_ZIPCODEINTL
			primary key,
	ZIPCODE VARCHAR(10) not null,
	ZIPCODETYPE VARCHAR(15),
	CITY VARCHAR(75),
	COUNTRY NUMBER
		constraint FK_DATAEXISTING_ZIPCODEINTL_COUNTRIES
			references PUBLIC.REFDATA_COUNTRIES,
	LATTITUDE VARCHAR(10),
	LONGITUDE VARCHAR(10),
	LOCATION VARCHAR(99),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_ZIPCODEINTL_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_ZIPCODEINTL_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAEXISTING_ZIPCODEUS
(
	ZIPCODEID NUMBER identity
		constraint PK_DATAEXISTING_ZIPCODEUS
			primary key,
	ZIPCODE VARCHAR(5) not null,
	ZIPCODETYPE VARCHAR(15),
	CITY VARCHAR(75),
	STATE VARCHAR(2),
	LATTITUDE VARCHAR(10),
	LONGITUDE VARCHAR(10),
	LOCATION VARCHAR(99),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAEXISTING_ZIPCODEUS_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAEXISTING_ZIPCODEUS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_ACCOUNTNUMBERS
(
	ACCOUNTNUMBERSID NUMBER identity
		constraint PK_DATAGENEERATED_ACCOUNTNUMBERS
			primary key,
	ACCOUNTNUMBERVALUE VARCHAR(20),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	CREATEDUSER VARCHAR(20),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_ACCOUNTNUMBERS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_ACCOUNTNUMBERS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_ADDRESSES
(
	ADDRESSID NUMBER identity
		constraint PK_DATAGENEERATED_ADDRESSES
			primary key,
	ADDRESSSTREET VARCHAR(99),
	ADDRESSSTREET2 VARCHAR(59),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_ADDRESSES_STATUS
			references PUBLIC.REFDATA_STATUS,
	ADDRESSFORMATTYPEID NUMBER default 1
		constraint FK_DATAGENERATED_ADDRESSES_ADDRESSFORMATTYPE
			references PUBLIC.REFDATA_ADDRESSFORMATTYPE,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_ADDRESSES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_BANKACCOUNT
(
	BANKACCOUNTSID NUMBER identity
		constraint PK_DATAGENEERATED_BANKACCOUNT
			primary key,
	BANKACCOUNTVALUE VARCHAR(17),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_BANKACCOUNT_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_BANKACCOUNT_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_CREDITCARD
(
	CREDITCARDID NUMBER identity
		constraint PK_DATAGENEERATED_CREDITCARD
			primary key,
	CREDITCARDNUMBER VARCHAR(20),
	CREDITCARDNAME VARCHAR(10),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_CREDITCARD_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_CREDITCARD_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_DATEOFBIRTH
(
	DATEOFBIRTHSID NUMBER identity
		constraint PK_DATAGENEERATED_DATEOFBIRTH
			primary key,
	DATEOFBIRTH VARCHAR(12),
	DATEOFBIRTHDATE DATE,
	AGE NUMBER,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_DATEOFBIRTH_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_DATEOFBIRTH_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_DRIVERSLICENSES
(
	DRIVERSLICENSESID NUMBER identity
		constraint PK_DATAGENEERATED_DRIVERSLICENSES
			primary key,
	DLN VARCHAR(25),
	STATECODE VARCHAR(2)
		constraint FK_DATAGENERATED_DRIVERSLICENSES_USSTATES
			references PUBLIC.REFDATA_USSTATES,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_DRIVERSLICENSES_STATUS
			references PUBLIC.REFDATA_STATUS,
	COMPLETEDRIVERSLICENSENUMBER VARCHAR(30),
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_DRIVERSLICENSES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_EIN
(
	EINID NUMBER identity
		constraint PK_DATAGENEERATED_EIN
			primary key,
	EINVALUE VARCHAR(10),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_EIN_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_EIN_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_PHONENUMBER
(
	PHONENUMBERID NUMBER identity
		constraint PK_DATAGENEERATED_PHONENUMBER
			primary key,
	PHONENUMBERVALUE VARCHAR(8),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_PHONENUMBERS_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_PHONENUMBER_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_PHONENUMBERSINTL
(
	PHONENUMBERINTLID NUMBER identity
		constraint PK_DATAGENEERATED_PHONENUMBERINTL
			primary key,
	PHONENUMBERVALUE VARCHAR(12),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_PHONENUMBERSINTL_STATUS
			references PUBLIC.REFDATA_STATUS,
	COUNTRYID NUMBER
		constraint FK_DATAGENERATED_PHONENUMBERSINTL_COUNTRY
			references PUBLIC.REFDATA_COUNTRIES,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_PHONENUMBERSINTL_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_SOCIALSECURITYNUMBER
(
	SOCIALSECURITYNUMBERID NUMBER identity
		constraint PK_DATAGENEERATED_SOCIALSECURITYNUMBER
			primary key,
	SOCIALSECURITYNUMBERVALUE VARCHAR(11),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_SOCIALSECURITYNUMBER_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_SOCIALSECURITYNUMBER_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.DATAGENERATED_USERIDENTITIES
(
	USERIDENTITIESID NUMBER identity
		constraint PK_DATAGENEERATED_USERIDENTITIES
			primary key,
	USERIDENTITYVALUE VARCHAR(20),
	USERDOMAIN VARCHAR(20),
	ADDITIONALATTRIBUTES VARCHAR(40),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_DATAGENERATED_USERIDENTITIES_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_DATAGENERATED_USERIDENTITIES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.PLATFORM_APPSETTING
(
	APPSETTINGSID NUMBER identity
		constraint PK_PLATFORM_APPSETTINGS
			primary key,
	APPSETTINGNAME VARCHAR(50),
	APPSETTINGVALUE VARCHAR(199),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_APPSETTINGS_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_PLATFORM_APPSETTINGS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION,
	DEFAULTDATAGENERATIONAPP VARCHAR(38)
		constraint FK_PLATFORM_APPSETTING_DATAGENAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.PLATFORM_DATAATTRIBUTES
(
	PLATFORMDATAATTRIBUTESID NUMBER identity
		constraint PK_PLATFORM_DATAATTRIBUTES
			primary key,
	DATAATTRIBUTENAME VARCHAR(50),
	SENSITIVITYFLAGID NUMBER
		constraint FK_PLATFORMDATAATTRIBUTES_SENSITIVTYFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_PLATFORMDATAATTRIBUTES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	PLATFORMDATAATTRIBUTEGUID VARCHAR(38),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_PLATFORM_DATAATTRIBUTES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.PLATFORM_CONFIG_DATAGEN
(
	DATAGENCONFIGID NUMBER identity
		constraint PK_PLATFORM_CONFIG_DATAGEN
			primary key,
	DATATYPEGENCONFIGNAME VARCHAR(25),
	DATAATTRIBUTEID NUMBER
		constraint FK_PLATFORM_DATAGENCONFIG_DATAATTRIBUTES
			references PUBLIC.PLATFORM_DATAATTRIBUTES,
	SPECIALINSTRUCTIONS VARCHAR(99),
	RUNQUANTITY NUMBER,
	MINUTEINTERVAL NUMBER,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_DATAGENCONFIG_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	APPLICATIONID VARCHAR(38)
		constraint PLATFORM_CONFIG_DATAGEN_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.PLATFORM_DATASTRUCTURES
(
	PLATFORMDATASTRUCTURESID NUMBER identity
		constraint PK_PLATFORM_DATASTRUCTURES
			primary key,
	DATASTRUCTURENAME VARCHAR(50),
	SENSITIVITYFLAGID NUMBER
		constraint FK_PLATFORM_DATASTRUCTURES_SENSITIVITYFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_DATASTRUCTURES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	PLATFORMDATASTRUCTURESGUID VARCHAR(38),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_PLATFORM_DATASTRUCTURES__REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.PLATFORM_DATASTRUCTURESTODATAATTRIBUTES
(
	PLATFORMDATASTRUCTURESTODATAATTRIBUTESID NUMBER identity
		constraint PK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES
			primary key,
	PLATFORMDATASTRUCTURESID NUMBER
		constraint FK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES_DATASTRUCTURE
			references PUBLIC.PLATFORM_DATASTRUCTURES,
	COMPOSITEDATASTRUCTURENAME VARCHAR(50),
	SENSITIVITYFLAGID NUMBER default 1
		constraint FK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES_SENSITIVITYFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	PLATFORMDATASTRUCTURESTODATAATTRIBUTESGUID VARCHAR(38),
	REGISTEREDAPP VARCHAR(38)
		constraint FK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION,
	PLATFORMDATAATTRIBUTESID NUMBER
		constraint FK_PLATFORM_DATASTRUCTURESTODATAATTRIBUTES_DATAATTRIBUTES
			references PUBLIC.PLATFORM_DATAATTRIBUTES
);

create or replace table PUBLIC.PLATFORM_RULESETSDEFINITIONS
(
	RULESETDEFINITIONSID VARCHAR(38) not null
		constraint PK_PLATFORM_RULESETDEFINTIONS
			primary key,
	RULESETDEFINITIONNAME VARCHAR(50),
	RULESETID NUMBER
		constraint FK_PLATFORM_RULESETSDEFINITIONS_RULESET
			references PUBLIC.PLATFORM_RULESETS,
	STEPORDERID NUMBER,
	OPERATIONTYPEID VARCHAR(7)
		constraint FK_PLATFORM_RULESETSDEFINITIONS_OPERATIONTYPE
			references PUBLIC.REFDATA_OPERATIONTYPE,
	RULESETDEFVALUE VARCHAR(40),
	STATUSID NUMBER default 1
		constraint FK_PLATFORM_RULESETSDEFINITIONS_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	EFFECTIVEDATE TIMESTAMPNTZ,
	APPLICATIONID VARCHAR(38)
		constraint FK_PLATFORM_RULESETSDEFINITIONS_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION,
	TERMDATE TIMESTAMPNTZ,
	DATAATTRIBUTEID NUMBER
		constraint FK_PLATFORM_RULESETSDEFINITIONS_DATAATTRIBUTES
			references PUBLIC.PLATFORM_DATAATTRIBUTES
);

create or replace table PUBLIC.REFDATA_PLATFORMPARAMSTODATAATTRIBUTES
(
	PLATFORMPARAMSTODATAATTRIBUTEID NUMBER identity
		constraint PK_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES
			primary key,
	PLATFORMPARAMSID NUMBER
		constraint FK_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES_PLATFORMPARAMS
			references PUBLIC.REFDATA_PLATFORMPARAMS,
	DATAATTRIBUTEID NUMBER
		constraint FK_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES_DATAATTRIBUTES
			references PUBLIC.PLATFORM_DATAATTRIBUTES,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES_STATUS
			references PUBLIC.REFDATA_STATUS,
	REGISTEREDAPP VARCHAR(38)
		constraint FK_REFDATA_PLATFORMPARAMSTODATAATTRIBUTES_REGISTEREDAPP
			references PUBLIC.REFDATA_APPLICATION
);

create or replace table PUBLIC.TERMS_CODESETSTOAPPLICATION
(
	CODESETTOAPPLICATIONID NUMBER identity
		constraint PK_TERMS_CODESETTOAPPLICATION
			primary key,
	CODESETSID NUMBER not null
		constraint FK_TERMS_CODESETSTOAPPLICATION_CODESET
			references PUBLIC.REFDATA_CODESET,
	DOMAIN VARCHAR(50),
	INDUSTRYSTD VARCHAR(6)
		constraint FK_TERMS_CODESETSTOAPPLICATION_INDUSTRYSTD
			references PUBLIC.REFDATA_INDUSTRYSTD,
	SPECIFICDETAILS VARCHAR(99),
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_TERMS_CODESETSTOAPPLICATION_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	ORGANIZATIONID VARCHAR(38)
		constraint FK_TERMS_CODESETSTOAPPLICATION_ORG
			references PUBLIC.REFDATA_ORGANIZATION,
	APPLICATIONID VARCHAR(38)
		constraint FK_TERMS_CODESETSTOAPPLICATION_APPLICATION
			references PUBLIC.REFDATA_APPLICATION,
	VENDORID NUMBER
		constraint FK_TERMS_CODESETSTOAPPLICATION_VENDOR
			references PUBLIC.REFDATA_VENDOR,
	CODEVALUE VARCHAR(20),
	CODEDESC VARCHAR(129),
	SENSITIVEFLAGID NUMBER
		constraint FK_TERMS_CODESETSTOAPPLICATION_SENSITIVEFLAG
			references PUBLIC.REFDATA_SENSITIVITYFLAG
);

create or replace table PUBLIC.TERMS_CODESETSTOAPPLICATIONVALUES
(
	CODESETTOAPPLICATIONVALUESID NUMBER identity
		constraint PK_TERMS_CODESETSTOAPPLICATIONVALUES
			primary key,
	CODESETTOAPPLICATIONID NUMBER
		constraint FK_TERMS_CODESETSTOAPPLICATIONVALUES_CODESETTOAPP
			references PUBLIC.TERMS_CODESETSTOAPPLICATION,
	CODESETSID NUMBER not null
		constraint FK_TERMS_CODESETSTOAPPLICATIONVALUES_CODESET
			references PUBLIC.REFDATA_CODESET,
	CREATEDDATE TIMESTAMPNTZ default CURRENT_TIMESTAMP(),
	STATUSID NUMBER default 1
		constraint FK_TERMS_CODESETSTOAPPLICATIONVALUES_STATUS
			references PUBLIC.REFDATA_STATUS,
	CREATEDUSER VARCHAR(20),
	TERMVALUE VARCHAR(20),
	TERMVALUELOW VARCHAR(10),
	TERMVALUEHIGH VARCHAR(10)
);

create or replace view comment 'The roles that can be applied to the current user.' INFORMATION_SCHEMA.APPLICABLE_ROLES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.APPLICABLE_ROLES.GRANTEE not supported: Role or user to whom the privilege is granted

-- comment on column INFORMATION_SCHEMA.APPLICABLE_ROLES.ROLE_NAME not supported: Name of the role

-- comment on column INFORMATION_SCHEMA.APPLICABLE_ROLES.ROLE_OWNER not supported: Owner of the role

-- comment on column INFORMATION_SCHEMA.APPLICABLE_ROLES.IS_GRANTABLE not supported: Whether this role can be granted to others

create or replace view comment 'The columns of tables defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.COLUMNS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.COLUMNS.TABLE_CATALOG not supported: Database that the table belongs to

-- comment on column INFORMATION_SCHEMA.COLUMNS.TABLE_SCHEMA not supported: Schema that the table belongs to

-- comment on column INFORMATION_SCHEMA.COLUMNS.TABLE_NAME not supported: Table that the column belongs to

-- comment on column INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME not supported: Name of the column

-- comment on column INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION not supported: Ordinal position of the column in the table

-- comment on column INFORMATION_SCHEMA.COLUMNS.COLUMN_DEFAULT not supported: Default value of the column

-- comment on column INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE not supported: 'YES' if the column may contain NULL, 'NO' otherwise

-- comment on column INFORMATION_SCHEMA.COLUMNS.DATA_TYPE not supported: Data type of the column

-- comment on column INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH not supported: Maximum length in characters of string columns

-- comment on column INFORMATION_SCHEMA.COLUMNS.CHARACTER_OCTET_LENGTH not supported: Maximum length in bytes of string columns

-- comment on column INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION not supported: Numeric precision of numeric columns

-- comment on column INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION_RADIX not supported: Radix of precision of numeric columns

-- comment on column INFORMATION_SCHEMA.COLUMNS.NUMERIC_SCALE not supported: Scale of numeric columns

-- comment on column INFORMATION_SCHEMA.COLUMNS.DATETIME_PRECISION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.INTERVAL_TYPE not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.INTERVAL_PRECISION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.CHARACTER_SET_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.CHARACTER_SET_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.CHARACTER_SET_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.COLLATION_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.COLLATION_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.COLLATION_NAME not supported: The name of collation, if present

-- comment on column INFORMATION_SCHEMA.COLUMNS.DOMAIN_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.DOMAIN_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.DOMAIN_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.UDT_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.UDT_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.UDT_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.SCOPE_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.SCOPE_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.SCOPE_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.MAXIMUM_CARDINALITY not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.DTD_IDENTIFIER not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IS_SELF_REFERENCING not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IS_IDENTITY not supported: Whether this column is an identity column

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_GENERATION not supported: Whether an identity column's value is always generated or only generated by default.  Snowflake only supports BY DEFAULT

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_START not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_INCREMENT not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_MAXIMUM not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_MINIMUM not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.COLUMNS.IDENTITY_CYCLE not supported: Whether the value of an identity column may cycle.  Snowflake only supports NO CYCLE.

-- comment on column INFORMATION_SCHEMA.COLUMNS.COMMENT not supported: Comment for this column

create or replace view comment 'The databases that are accessible to the current user''s role.' INFORMATION_SCHEMA.DATABASES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.DATABASES.DATABASE_NAME not supported: Name of the database

-- comment on column INFORMATION_SCHEMA.DATABASES.DATABASE_OWNER not supported: Name of the role that owns the schema

-- comment on column INFORMATION_SCHEMA.DATABASES.IS_TRANSIENT not supported: Whether this is a transient table

-- comment on column INFORMATION_SCHEMA.DATABASES.COMMENT not supported: Comment for this database

-- comment on column INFORMATION_SCHEMA.DATABASES.CREATED not supported: Creation time of the database

-- comment on column INFORMATION_SCHEMA.DATABASES.LAST_ALTERED not supported: Last altered time of the database

-- comment on column INFORMATION_SCHEMA.DATABASES.RETENTION_TIME not supported: Number of days that historical data is retained for Time Travel

create or replace view comment 'The roles that are enabled to the current user.' INFORMATION_SCHEMA.ENABLED_ROLES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.ENABLED_ROLES.ROLE_NAME not supported: Name of the role

-- comment on column INFORMATION_SCHEMA.ENABLED_ROLES.ROLE_OWNER not supported: Owner of the role

create or replace view comment 'The external tables defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.EXTERNAL_TABLES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.TABLE_CATALOG not supported: Database that the external table belongs to

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.TABLE_SCHEMA not supported: Schema that the external table belongs to

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.TABLE_NAME not supported: Name of the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.TABLE_OWNER not supported: Name of the role that owns the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.CREATED not supported: Creation time of the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.LAST_ALTERED not supported: Last altered time of the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.COMMENT not supported: Comment for this external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.LOCATION not supported: Location of the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.FILE_FORMAT_NAME not supported: File format name (if there is one) of the external table

-- comment on column INFORMATION_SCHEMA.EXTERNAL_TABLES.FILE_FORMAT_TYPE not supported: File format type (if not named) of the external table

create or replace view comment 'The file formats defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.FILE_FORMATS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FILE_FORMAT_CATALOG not supported: Database that the file format belongs to

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FILE_FORMAT_SCHEMA not supported: Schema that the file format belongs to

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FILE_FORMAT_NAME not supported: Name of the file format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FILE_FORMAT_OWNER not supported: Name of the role that owns the file format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FILE_FORMAT_TYPE not supported: Type of the file format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.RECORD_DELIMITER not supported: Character that separates records

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FIELD_DELIMITER not supported: Character that separates fields

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.SKIP_HEADER not supported: Number of lines skipped at the start of the file

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.DATE_FORMAT not supported: Date format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.TIME_FORMAT not supported: Time format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.TIMESTAMP_FORMAT not supported: Timestamp format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.BINARY_FORMAT not supported: Binary format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.ESCAPE not supported: String used as the escape character for any field values

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.ESCAPE_UNENCLOSED_FIELD not supported: String used as the escape character for unenclosed field values

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.TRIM_SPACE not supported: Whether whitespace is removed from fields

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.FIELD_OPTIONALLY_ENCLOSED_BY not supported: Character used to enclose strings

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.NULL_IF not supported: A list of strings to be replaced by null

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.COMPRESSION not supported: Compression method for the data file

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.ERROR_ON_COLUMN_COUNT_MISMATCH not supported: Whether to generate a parsing error if the number of fields in an input file does not match the number of columns in the corresponding table

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.CREATED not supported: Creation time of the file format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.LAST_ALTERED not supported: Last altered time of the file format

-- comment on column INFORMATION_SCHEMA.FILE_FORMATS.COMMENT not supported: Comment for this file format

create or replace view comment 'The user-defined functions defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.FUNCTIONS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_CATALOG not supported: Database which the function belongs to

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_SCHEMA not supported: Schema which the function belongs to

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_NAME not supported: Name of the function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_OWNER not supported: Name of the role that owns the function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.ARGUMENT_SIGNATURE not supported: Type signature of the function's arguments

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.DATA_TYPE not supported: Return value data type

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.CHARACTER_MAXIMUM_LENGTH not supported: Maximum length in characters of string return value

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.CHARACTER_OCTET_LENGTH not supported: Maximum length in bytes of string return value

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.NUMERIC_PRECISION not supported: Numeric precision of numeric return value

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.NUMERIC_PRECISION_RADIX not supported: Radix of precision of numeric return value

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.NUMERIC_SCALE not supported: Scale of numeric return value

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_LANGUAGE not supported: Language of the function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.FUNCTION_DEFINITION not supported: Function definition

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.VOLATILITY not supported: Whether the function is volatile or immutable

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.IS_NULL_CALL not supported: Whether the function is called on null input

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.IS_SECURE not supported: Whether this function is secure.

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.CREATED not supported: Creation time of the function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.LAST_ALTERED not supported: Last altered time of the function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.COMMENT not supported: Comment for this function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.IS_EXTERNAL not supported: Whether this function is external

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.API_INTEGRATION not supported: Integration for this function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.CONTEXT_HEADERS not supported: Context headers for this function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.MAX_BATCH_ROWS not supported: Max batch rows for this function

-- comment on column INFORMATION_SCHEMA.FUNCTIONS.COMPRESSION not supported: Type of compression used for serializing function payload

create or replace view comment 'Identifies the database (or catalog, in SQL terminology) that contains the information_schema' INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME.CATALOG_NAME not supported: The name of the database in which this information_schema resides.

create or replace view comment 'The loading information of the copy command' INFORMATION_SCHEMA.LOAD_HISTORY as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.SCHEMA_NAME not supported: Schema of target table

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.FILE_NAME not supported: Name of source file

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.TABLE_NAME not supported: Name of target table

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.LAST_LOAD_TIME not supported: Timestamp of the load record

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.STATUS not supported: Status: loaded, load failed or partially loaded

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.ROW_COUNT not supported: Number of rows loaded from the source file

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.ROW_PARSED not supported: Number of rows parsed from the source file

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.FIRST_ERROR_MESSAGE not supported: First error of the source file

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.FIRST_ERROR_LINE_NUMBER not supported: Line number of the first error

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.FIRST_ERROR_CHARACTER_POSITION not supported: Position of the first error character

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.FIRST_ERROR_COL_NAME not supported: Column name of the first error

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.ERROR_COUNT not supported: Number of error rows in the source file

-- comment on column INFORMATION_SCHEMA.LOAD_HISTORY.ERROR_LIMIT not supported: If the number of error reach this limit, then abort

create or replace view comment 'The privileges on all objects defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.OBJECT_PRIVILEGES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.GRANTOR not supported: Role who granted the privilege

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.GRANTEE not supported: Role to whom the privilege is granted

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.OBJECT_CATALOG not supported: Database containing the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.OBJECT_SCHEMA not supported: Schema containing the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.OBJECT_NAME not supported: Name of the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.OBJECT_TYPE not supported: Type of the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.PRIVILEGE_TYPE not supported: Type of the granted privilege

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.IS_GRANTABLE not supported: Whether the privilege was granted WITH GRANT OPTION

-- comment on column INFORMATION_SCHEMA.OBJECT_PRIVILEGES.CREATED not supported: Creation time of the privilege

create or replace view comment 'The pipes defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.PIPES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.PIPES.PIPE_CATALOG not supported: Database that the pipe belongs to

-- comment on column INFORMATION_SCHEMA.PIPES.PIPE_SCHEMA not supported: Schema that the pipe belongs to

-- comment on column INFORMATION_SCHEMA.PIPES.PIPE_NAME not supported: Name of the pipe

-- comment on column INFORMATION_SCHEMA.PIPES.PIPE_OWNER not supported: Name of the role that owns the pipe

-- comment on column INFORMATION_SCHEMA.PIPES.DEFINITION not supported: Definition of the pipe as it was created

-- comment on column INFORMATION_SCHEMA.PIPES.IS_AUTOINGEST_ENABLED not supported: Whether this is an auto-ingest tpipe

-- comment on column INFORMATION_SCHEMA.PIPES.NOTIFICATION_CHANNEL_NAME not supported: Notification channel name if it is an auto-ingest pipe

-- comment on column INFORMATION_SCHEMA.PIPES.CREATED not supported: Creation time of the pipe

-- comment on column INFORMATION_SCHEMA.PIPES.LAST_ALTERED not supported: Last altered time of the pipe

-- comment on column INFORMATION_SCHEMA.PIPES.COMMENT not supported: Comment for this pipe

-- comment on column INFORMATION_SCHEMA.PIPES.PATTERN not supported: Pattern used to filter the files in Snowpipe

create or replace view comment 'The stored procedures defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.PROCEDURES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_CATALOG not supported: Database which the procedure belongs to

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_SCHEMA not supported: Schema which the procedure belongs to

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_NAME not supported: Name of the procedure

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_OWNER not supported: Name of the role that owns the procedure

-- comment on column INFORMATION_SCHEMA.PROCEDURES.ARGUMENT_SIGNATURE not supported: Type signature of the procedure's arguments

-- comment on column INFORMATION_SCHEMA.PROCEDURES.DATA_TYPE not supported: Return value data type

-- comment on column INFORMATION_SCHEMA.PROCEDURES.CHARACTER_MAXIMUM_LENGTH not supported: Maximum length in characters of string return value

-- comment on column INFORMATION_SCHEMA.PROCEDURES.CHARACTER_OCTET_LENGTH not supported: Maximum length in bytes of string return value

-- comment on column INFORMATION_SCHEMA.PROCEDURES.NUMERIC_PRECISION not supported: Numeric precision of numeric return value

-- comment on column INFORMATION_SCHEMA.PROCEDURES.NUMERIC_PRECISION_RADIX not supported: Radix of precision of numeric return value

-- comment on column INFORMATION_SCHEMA.PROCEDURES.NUMERIC_SCALE not supported: Scale of numeric return value

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_LANGUAGE not supported: Language of the procedure

-- comment on column INFORMATION_SCHEMA.PROCEDURES.PROCEDURE_DEFINITION not supported: Procedure definition

-- comment on column INFORMATION_SCHEMA.PROCEDURES.CREATED not supported: Creation time of the procedure

-- comment on column INFORMATION_SCHEMA.PROCEDURES.LAST_ALTERED not supported: Last altered time of the procedure

-- comment on column INFORMATION_SCHEMA.PROCEDURES.COMMENT not supported: Comment for this procedure

create or replace view comment 'Referential Constraints in this database that are accessible to the current user' INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_CATALOG not supported: Database that the constraint belongs to

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_SCHEMA not supported: Schema that the constraint belongs to

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME not supported: Name of the constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_CATALOG not supported: Database of the unique constraint referenced by the current constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_SCHEMA not supported: Schema of the unique constraint referenced by the current constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME not supported: Name of the unique constraint referenced by the current constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.MATCH_OPTION not supported: Match option for the constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UPDATE_RULE not supported: Update Rule for the current constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.DELETE_RULE not supported: Delete Rule for the current constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.COMMENT not supported: Comment for this constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CREATED not supported: Creation time of the constraint

-- comment on column INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.LAST_ALTERED not supported: Last altered time of the constraint

create or replace view comment 'The databases for replication that are accessible to the current user''s role.' INFORMATION_SCHEMA.REPLICATION_DATABASES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.REGION_GROUP not supported: Region group of this database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.SNOWFLAKE_REGION not supported: Snowflake region of this database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.ACCOUNT_NAME not supported: Name of the account that owns the database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.DATABASE_NAME not supported: Name of the database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.COMMENT not supported: Comment for this database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.CREATED not supported: Creation time of the database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.IS_PRIMARY not supported: Whether this database is the primary

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.PRIMARY not supported: Primary database of this replication group

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.REPLICATION_ALLOWED_TO_ACCOUNTS not supported: List of accounts that can host secondary replicas for this database

-- comment on column INFORMATION_SCHEMA.REPLICATION_DATABASES.FAILOVER_ALLOWED_TO_ACCOUNTS not supported: List of accounts that can host primary replicas for this database

create or replace view comment 'The schemas defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.SCHEMATA as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.SCHEMATA.CATALOG_NAME not supported: Database that the schema belongs to

-- comment on column INFORMATION_SCHEMA.SCHEMATA.SCHEMA_NAME not supported: Name of the schema

-- comment on column INFORMATION_SCHEMA.SCHEMATA.SCHEMA_OWNER not supported: Name of the role that owns the schema

-- comment on column INFORMATION_SCHEMA.SCHEMATA.IS_TRANSIENT not supported: Whether this is a transient table

-- comment on column INFORMATION_SCHEMA.SCHEMATA.IS_MANAGED_ACCESS not supported: Whether this is a managed access schema

-- comment on column INFORMATION_SCHEMA.SCHEMATA.RETENTION_TIME not supported: Number of days that historical data is retained for Time Travel

-- comment on column INFORMATION_SCHEMA.SCHEMATA.DEFAULT_CHARACTER_SET_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SCHEMATA.DEFAULT_CHARACTER_SET_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SCHEMATA.DEFAULT_CHARACTER_SET_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SCHEMATA.SQL_PATH not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SCHEMATA.CREATED not supported: Creation time of the schema

-- comment on column INFORMATION_SCHEMA.SCHEMATA.LAST_ALTERED not supported: Last altered time of the schema

-- comment on column INFORMATION_SCHEMA.SCHEMATA.COMMENT not supported: Comment for this schema

create or replace view comment 'The sequences defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.SEQUENCES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_CATALOG not supported: Database that the sequence belongs to

-- comment on column INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_SCHEMA not supported: Schema that the sequence belongs to

-- comment on column INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_NAME not supported: Name of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.SEQUENCE_OWNER not supported: Name of the role that owns the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.DATA_TYPE not supported: Data type of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.NUMERIC_PRECISION not supported: Numeric precision of the data type of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.NUMERIC_PRECISION_RADIX not supported: Radix of the numeric precision of the data type of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.NUMERIC_SCALE not supported: Scale of the data type of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.START_VALUE not supported: Initial value of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.MINIMUM_VALUE not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SEQUENCES.MAXIMUM_VALUE not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SEQUENCES.NEXT_VALUE not supported: Next value that the sequence will produce

-- comment on column INFORMATION_SCHEMA.SEQUENCES."INCREMENT" not supported: Increment of the sequence generator

-- comment on column INFORMATION_SCHEMA.SEQUENCES.CYCLE_OPTION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.SEQUENCES.CREATED not supported: Creation time of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.LAST_ALTERED not supported: Last altered time of the sequence

-- comment on column INFORMATION_SCHEMA.SEQUENCES.COMMENT not supported: Comment for this sequence

create or replace view comment 'Stages in this database that are accessible by the current user''s role' INFORMATION_SCHEMA.STAGES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_CATALOG not supported: Database that the stage belongs to

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_SCHEMA not supported: Schema that the stage belongs to

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_NAME not supported: Name of the stage

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_URL not supported: Location of an external stage

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_REGION not supported: AWS region where the stage resides

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_TYPE not supported: Type of stage: User, Table, Internal Named or External Named

-- comment on column INFORMATION_SCHEMA.STAGES.STAGE_OWNER not supported: Name of the role that owns the stage

-- comment on column INFORMATION_SCHEMA.STAGES.COMMENT not supported: Comment for this stage

-- comment on column INFORMATION_SCHEMA.STAGES.CREATED not supported: Creation time of the stage

-- comment on column INFORMATION_SCHEMA.STAGES.LAST_ALTERED not supported: Last altered time of the stage

create or replace view comment 'The tables defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.TABLES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.TABLES.TABLE_CATALOG not supported: Database that the table belongs to

-- comment on column INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA not supported: Schema that the table belongs to

-- comment on column INFORMATION_SCHEMA.TABLES.TABLE_NAME not supported: Name of the table

-- comment on column INFORMATION_SCHEMA.TABLES.TABLE_OWNER not supported: Name of the role that owns the table

-- comment on column INFORMATION_SCHEMA.TABLES.TABLE_TYPE not supported: Whether the table is a base table, temporary table, or view

-- comment on column INFORMATION_SCHEMA.TABLES.IS_TRANSIENT not supported: Whether this is a transient table

-- comment on column INFORMATION_SCHEMA.TABLES.CLUSTERING_KEY not supported: Clustering key for the table

-- comment on column INFORMATION_SCHEMA.TABLES.ROW_COUNT not supported: Number of rows in the table

-- comment on column INFORMATION_SCHEMA.TABLES.BYTES not supported: Number of bytes accessed by a scan of the table

-- comment on column INFORMATION_SCHEMA.TABLES.RETENTION_TIME not supported: Number of days that historical data is retained for Time Travel

-- comment on column INFORMATION_SCHEMA.TABLES.SELF_REFERENCING_COLUMN_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.REFERENCE_GENERATION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.USER_DEFINED_TYPE_CATALOG not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.USER_DEFINED_TYPE_SCHEMA not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.USER_DEFINED_TYPE_NAME not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.IS_INSERTABLE_INTO not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.IS_TYPED not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.COMMIT_ACTION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLES.CREATED not supported: Creation time of the function

-- comment on column INFORMATION_SCHEMA.TABLES.LAST_ALTERED not supported: Last altered time of the function

-- comment on column INFORMATION_SCHEMA.TABLES.AUTO_CLUSTERING_ON not supported: Whether automatic clustering is on for the table

-- comment on column INFORMATION_SCHEMA.TABLES.COMMENT not supported: Comment for this table

create or replace view comment 'Constraints defined on the tables in this database that are accessible to the current user' INFORMATION_SCHEMA.TABLE_CONSTRAINTS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_CATALOG not supported: Database that the constraint belongs to

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_SCHEMA not supported: Schema that the constraint belongs to

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME not supported: Name of the constraint

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_CATALOG not supported: Name of the database of the current table

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_SCHEMA not supported: Name of the schema of the current table

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME not supported: Name of the current table

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE not supported: Type of the constraint

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.IS_DEFERRABLE not supported: Whether evaluation of the constraint can be deferred

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.INITIALLY_DEFERRED not supported: Whether evaluation of the constraint is deferrable and initially deferred

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.ENFORCED not supported: Whether the constraint is enforced

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.COMMENT not supported: Comment for this constraint

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CREATED not supported: Creation time of the constraint

-- comment on column INFORMATION_SCHEMA.TABLE_CONSTRAINTS.LAST_ALTERED not supported: Last altered time of the constraint

create or replace view comment 'The privileges on tables defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.TABLE_PRIVILEGES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.GRANTOR not supported: Role who granted the table privilege

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.GRANTEE not supported: Role to whom the table privilege is granted

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.TABLE_CATALOG not supported: Database containing the table on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.TABLE_SCHEMA not supported: Schema containing the table on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.TABLE_NAME not supported: Name of the table on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.PRIVILEGE_TYPE not supported: Type of the granted privilege

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.IS_GRANTABLE not supported: Whether the privilege was granted WITH GRANT OPTION

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.WITH_HIERARCHY not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.TABLE_PRIVILEGES.CREATED not supported: Creation time of the privilege

create or replace view comment 'All tables within an account, including expired tables.' INFORMATION_SCHEMA.TABLE_STORAGE_METRICS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_CATALOG not supported: Database that the table belongs to.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_SCHEMA not supported: Schema that the table belongs to.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_NAME not supported: Name of the table.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.ID not supported: Unique identifier of the table

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.CLONE_GROUP_ID not supported: Unique identifier of the oldest clone ancestor of this table.  Same as this table's ID if it is not a clone.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.IS_TRANSIENT not supported: 'YES' if table is transient, 'NO' otherwise.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.ACTIVE_BYTES not supported: Bytes in the active version of the table. Some bytes may be billed to another table if this table is a clone.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TIME_TRAVEL_BYTES not supported: Bytes in time travel versions of the table. Some bytes may be billed to another table if this table is a clone

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.FAILSAFE_BYTES not supported: Bytes in failsafe versions of the table. All such bytes are billed to this table.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.RETAINED_FOR_CLONE_BYTES not supported: Bytes which used to be owned by this table and are no longer referenced by it. Still, they are retained (and billed) because other clone(s) of that table are still referencing these bytes. Note that the original metadata for this table might have been purged so the table, schema, and database names might be NULL in this case.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_CREATED not supported: Time at which this table was created.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_DROPPED not supported: Time at which the table was dropped, or NULL.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.TABLE_ENTERED_FAILSAFE not supported: Time at which the table entered the failsafe state, or NULL.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.CATALOG_CREATED not supported: Time at which the database was created.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.CATALOG_DROPPED not supported: Time at which the database was dropped.  Potentially NULL if table is past failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.SCHEMA_CREATED not supported: Time at which the schema was created.  Potentially NULL if table is past failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.SCHEMA_DROPPED not supported: Time at which the schema was dropped.  Potentially NULL if table is in failsafe.

-- comment on column INFORMATION_SCHEMA.TABLE_STORAGE_METRICS.COMMENT not supported: Table's comment.  Potentially NULL if table is in failsafe.

create or replace view comment 'The usage privileges on sequences defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.USAGE_PRIVILEGES as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.GRANTOR not supported: Role who granted the usage privilege

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.GRANTEE not supported: Role to whom the usage privilege is granted

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.OBJECT_CATALOG not supported: Database containing the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.OBJECT_SCHEMA not supported: Schema containing the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.OBJECT_NAME not supported: Name of the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.OBJECT_TYPE not supported: Type of the object on which the privilege is granted

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.PRIVILEGE_TYPE not supported: Type of the granted privilege

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.IS_GRANTABLE not supported: Whether the privilege was granted WITH GRANT OPTION

-- comment on column INFORMATION_SCHEMA.USAGE_PRIVILEGES.CREATED not supported: Creation time of the privilege

create or replace view comment 'The views defined in this database that are accessible to the current user''s role.' INFORMATION_SCHEMA.VIEWS as
	-- missing source code
;

-- comment on column INFORMATION_SCHEMA.VIEWS.TABLE_CATALOG not supported: Database that the view belongs to

-- comment on column INFORMATION_SCHEMA.VIEWS.TABLE_SCHEMA not supported: Schema that the view belongs to

-- comment on column INFORMATION_SCHEMA.VIEWS.TABLE_NAME not supported: Name of the view

-- comment on column INFORMATION_SCHEMA.VIEWS.TABLE_OWNER not supported: Name of the role that owns the view

-- comment on column INFORMATION_SCHEMA.VIEWS.VIEW_DEFINITION not supported: Text of the view's query expression

-- comment on column INFORMATION_SCHEMA.VIEWS.CHECK_OPTION not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.VIEWS.IS_UPDATABLE not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.VIEWS.INSERTABLE_INTO not supported: Not applicable for Snowflake.

-- comment on column INFORMATION_SCHEMA.VIEWS.IS_SECURE not supported: Whether this view is secure.

-- comment on column INFORMATION_SCHEMA.VIEWS.CREATED not supported: Creation time of the view

-- comment on column INFORMATION_SCHEMA.VIEWS.LAST_ALTERED not supported: Last altered time of the view

-- comment on column INFORMATION_SCHEMA.VIEWS.COMMENT not supported: Comment for this view

