---
version: "3"
services:
  datasynthesisdb:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: datasynthesis
    # volumes:
    #   - ../DataTier/MySQL/DDL/2021/datasynthesis-2021-0312.sql:/docker-entrypoint-initdb.d/001.sql:Z,delegated
    #   - ../DataTier/MySQL/MySQL-DumpFiles/complete-datasynthesis-08222020.sql:/docker-entrypoint-initdb.d/002.sql:Z,delegated
  quarkus:
    image: maven
    environment:
      DATABASE_HOST: datasynthesisdb
    volumes:
      - "./:/app:Z,delegated"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "~/.m2:/root/.m2:Z,delegated"
    ports:
      - 5005:5005 # Debug port
      - 8080:8080 # Backend HTTP server port
    working_dir: /app
    command: "mvn quarkus:dev"
    links:
      - datasynthesisdb
    depends_on:
      - datasynthesisdb
