version: "3.9"

services:
  hapi-fhir:
    image: hapiproject/hapi:v5.7.0
    hostname: hapi-fhir
    container_name: hapi-fhir
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - hapi-fhir-postgres
    environment:
      JAVA_OPTS: -Dhapi.properties=/config/hapi.properties
    volumes:
      - ./config:/config

  hapi-fhir-postgres:
    image: postgres:14.2
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: posgres
    volumes:
      - hapi-fhir-postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.1
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  hapi-fhir-postgres-data:
    driver: local
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local