insert into refdata_terminologystd (TerminologyStd, TerminologyStdVersion, TerminologyStdDesc)
values  ('AIR', '1995AA', 'AI/RHEUM'),
        ('ALT', '2009AA', 'Alternative Billing Concepts'),
        ('AOD', '2002AC', 'Alcohol and Other Drug Thesaurus'),
        ('AOT', '2006AD', 'Authorized Osteopathic Thesaurus'),
        ('ATC', '2021AA', 'Anatomical Therapeutic Chemical Classification System'),
        ('BI', '1999AA', 'Beth Israel Problem List'),
        ('CCC', '2018AA', 'Clinical Care Classification'),
        ('CCPSS', '2000AA', 'Clinical Problem Statements'),
        ('CCS', '2005AC', 'Clinical Classifications Software'),
        ('CCSR_ICD10CM', '2021AA', 'Clinical Classifications Software Refined for ICD-10-CM'),
        ('CCSR_ICD10PCS', '2021AA', 'Clinical Classifications Software Refined for ICD-10-PCS'),
        ('CDT', '2020AB', 'CDT'),
        ('CHV', '2012AA', 'Consumer Health Vocabulary'),
        ('COSTAR', '2002AD', 'COSTAR'),
        ('CPM', '2003AC', 'Medical Entities Dictionary'),
        ('CPT', '2021AA', 'CPT - Current Procedural Terminology'),
        ('CPTSP', '2001AC', 'CPT Spanish'),
        ('CSP', '2006AB', 'CRISP Thesaurus'),
        ('CST', '1999AA', 'COSTART'),
        ('CVX', '2021AA', 'Vaccines Administered'),
        ('DDB', '2001AA', 'Diseases Database'),
        ('DMDICD10', '1997AA', 'ICD-10 German'),
        ('DMDUMD', '1999AA', 'UMDNS German'),
        ('DRUGBANK', '2021AA', 'DrugBank'),
        ('DSM-5', '2016AB', 'Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition'),
        ('DXP', '1995AA', 'DXplain'),
        ('FMA', '2019AB', 'Foundational Model of Anatomy'),
        ('GO', '2020AB', 'Gene Ontology'),
        ('GS', '2021AA', 'Gold Standard Drug Database'),
        ('HCDT', '2021AA', 'CDT in HCPCS'),
        ('HCPCS', '2021AA', 'HCPCS - Healthcare Common Procedure Coding System'),
        ('HCPT', '2021AA', 'CPT in HCPCS'),
        ('HGNC', '2020AB', 'HUGO Gene Nomenclature Committee'),
        ('HL7V2.5', '2005AC', 'HL7 Version 2.5'),
        ('HL7V3.0', '2021AA', 'HL7 Version 3.0'),
        ('HLREL', '2001AA', 'ICPC2E ICD10 Relationships'),
        ('HPO', '2021AA', 'Human Phenotype Ontology'),
        ('ICD10AE', '1998AA', 'ICD-10, American English Equivalents'),
        ('ICD10AM', '2000AB', 'ICD-10, Australian Modification'),
        ('ICD10AMAE', '2002AD', 'ICD-10, Australian Modification, Americanized English Equivalents'),
        ('ICD10DUT', '2004AB', 'ICD10, Dutch Translation'),
        ('ICD10PCS', '2020AB', 'ICD-10 Procedure Coding System'),
        ('ICF', '2009AA', 'International Classification of Functioning, Disability and Health'),
        ('ICNP', '2019AB', 'International Classification for Nursing Practice'),
        ('ICPC', '1998AA', 'International Classification of Primary Care'),
        ('ICPC2EDUT', '2004AB', 'ICPC2E Dutch'),
        ('ICPC2EENG', '2004AB', 'International Classification of Primary Care, 2nd Edition, Electronic'),
        ('ICPC2ICD10DUT', '2005AB', 'ICPC2-ICD10 Thesaurus, Dutch Translation'),
        ('ICPC2ICD10ENG', '2005AB', 'ICPC2-ICD10 Thesaurus'),
        ('ICPC2P', '2006AB', 'ICPC-2 PLUS'),
        ('ICPCBAQ', '2000AA', 'ICPC Basque'),
        ('ICPCDAN', '1999AA', 'ICPC Danish'),
        ('ICPCDUT', '1999AA', 'ICPC Dutch'),
        ('ICPCFIN', '1999AA', 'ICPC Finnish'),
        ('ICPCFRE', '2000AA', 'ICPC French'),
        ('ICPCGER', '2000AA', 'ICPC German'),
        ('ICPCHEB', '2000AA', 'ICPC Hebrew'),
        ('ICPCHUN', '1999AA', 'ICPC Hungarian'),
        ('ICPCITA', '1999AA', 'ICPC Italian'),
        ('ICPCNOR', '1999AA', 'ICPC Norwegian'),
        ('ICPCPOR', '1999AA', 'ICPC Portuguese'),
        ('ICPCSPA', '2000AA', 'ICPC Spanish'),
        ('ICPCSWE', '2000AA', 'ICPC Swedish'),
        ('JABL', '2000AA', 'Congenital Mental Retardation Syndromes'),
        ('KCD5', '2009AA', 'Korean Standard Classification of Disease Version 5'),
        ('LCH', '1992AA', 'Library of Congress Subject Headings'),
        ('LCH_NW', '2014AB', 'Library of Congress Subject Headings, Northwestern University subset'),
        ('LNC', '2021AA', 'LOINC'),
        ('LNC-DE-AT', '2021AA', 'LOINC Linguistic Variant - German, Austria'),
        ('LNC-DE-DE', '2021AA', 'LOINC Linguistic Variant - German, Germany'),
        ('LNC-EL-GR', '2021AA', 'LOINC Linguistic Variant - Greek, Greece'),
        ('LNC-ES-AR', '2021AA', 'LOINC Linguistic Variant - Spanish, Argentina'),
        ('LNC-ES-ES', '2021AA', 'LOINC Linguistic Variant - Spanish, Spain'),
        ('LNC-ET-EE', '2021AA', 'LOINC Linguistic Variant - Estonian, Estonia'),
        ('LNC-FR-BE', '2021AA', 'LOINC Linguistic Variant - French, Belgium'),
        ('LNC-FR-CA', '2021AA', 'LOINC Linguistic Variant - French, Canada'),
        ('LNC-FR-FR', '2021AA', 'LOINC Linguistic Variant - French, France'),
        ('LNC-IT-IT', '2021AA', 'LOINC Linguistic Variant - Italian, Italy'),
        ('LNC-KO-KR', '2021AA', 'LOINC Linguistic Variant - Korea, Korean'),
        ('LNC-NL-NL', '2021AA', 'LOINC Linguistic Variant - Dutch, Netherlands'),
        ('LNC-PT-BR', '2021AA', 'LOINC Linguistic Variant - Portuguese, Brazil'),
        ('LNC-RU-RU', '2021AA', 'LOINC Linguistic Variant - Russian, Russia'),
        ('LNC-TR-TR', '2021AA', 'LOINC Linguistic Variant - Turkish, Turkey'),
        ('LNC-ZH-CN', '2021AA', 'LOINC Linguistic Variant - Chinese, China'),
        ('MCM', '1992AA', 'Glossary of Clinical Epidemiologic Terms'),
        ('MDR', '2021AA', 'MedDRA'),
        ('MDRBPO', '2021AA', 'MedDRA Brazilian Portuguese'),
        ('MDRCZE', '2021AA', 'MedDRA Czech'),
        ('MDRDUT', '2021AA', 'MedDRA Dutch'),
        ('MDRFRE', '2021AA', 'MedDRA French'),
        ('MDRGER', '2021AA', 'MedDRA German'),
        ('MDRHUN', '2021AA', 'MedDRA Hungarian'),
        ('MDRITA', '2021AA', 'MedDRA Italian'),
        ('MDRJPN', '2021AA', 'MedDRA Japanese'),
        ('MDRKOR', '2021AA', 'MedDRA Korean'),
        ('MDRPOR', '2021AA', 'MedDRA Portuguese'),
        ('MDRRUS', '2021AA', 'MedDRA Russian'),
        ('MDRSPA', '2021AA', 'MedDRA Spanish'),
        ('MED-RT', '2021AA', 'Medication Reference Terminology'),
        ('MEDCIN', '2021AA', 'MEDCIN'),
        ('MEDLINEPLUS', '2021AA', 'MedlinePlus Health Topics'),
        ('MEDLINEPLUS_SPA', '2021AA', 'MEDLINEPLUS Spanish'),
        ('MMSL', '2021AA', 'Multum'),
        ('MMX', '2021AA', 'Micromedex'),
        ('MSH', '2021AA', 'MeSH'),
        ('MSHCZE', '2021AA', 'MeSH Czech'),
        ('MSHDUT', '2005AB', 'MeSH Dutch'),
        ('MSHFIN', '2008AA', 'MeSH Finnish'),
        ('MSHFRE', '2021AA', 'MeSH French'),
        ('MSHGER', '2019AA', 'MeSH German'),
        ('MSHITA', '2019AA', 'MeSH Italian'),
        ('MSHJPN', '2015AB', 'MeSH Japanese'),
        ('MSHLAV', '2012AA', 'MeSH Latvian'),
        ('MSHNOR', '2019AA', 'MeSH Norwegian'),
        ('MSHPOL', '2021AA', 'MeSH Polish'),
        ('MSHPOR', '2020AA', 'MeSH Portuguese'),
        ('MSHRUS', '2021AA', 'MeSH Russian'),
        ('MSHSCR', '2019AA', 'MeSH Croatian'),
        ('MSHSPA', '2020AA', 'MeSH Spanish'),
        ('MSHSWE', '2020AA', 'MeSH Swedish'),
        ('MTH', '1990AA', 'Metathesaurus Names'),
        ('MTHCMSFRF', '2021AA', 'Metathesaurus CMS Formulary Reference File'),
        ('MTHICD9', '2015AA', 'ICD-9-CM Entry Terms'),
        ('MTHICPC2EAE', '2004AB', 'ICPC2E American English Equivalents'),
        ('MTHICPC2ICD10AE', '2005AB', 'ICPC2E-ICD10 Thesaurus, American English Equivalents'),
        ('MTHMST', '2002AA', 'Minimal Standard Terminology (UMLS)'),
        ('MTHMSTFRE', '2002AA', 'Minimal Standard Terminology French (UMLS)'),
        ('MTHMSTITA', '2002AA', 'Minimal Standard Terminology Italian (UMLS)'),
        ('MTHSPL', '2021AA', 'FDA Structured Product Labels'),
        ('MVX', '2021AA', 'Manufacturers of Vaccines'),
        ('NANDA-I', '2018AA', 'NANDA-I Taxonomy'),
        ('NCBI', '2020AB', 'NCBI Taxonomy'),
        ('NCI', '2021AA', 'NCI Thesaurus'),
        ('NCI_BioC', '2021AA', 'BioCarta online maps of molecular pathways, adapted for NCI use'),
        ('NCI_BRIDG', '2021AA', 'Biomedical Research Integrated Domain Group Model Subset'),
        ('NCI_BRIDG_3_0_3', '2021AA', 'Biomedical Research Integrated Domain Group Model, 3.0.3'),
        ('NCI_BRIDG_5_3', '2021AA', 'Biomedical Research Integrated Domain Group Model, 5.3'),
        ('NCI_caDSR', '2021AA', 'Cancer Data Standards Registry and Repository'),
        ('NCI_CareLex', '2021AA', 'Content Archive Resource Exchange Lexicon'),
        ('NCI_CBDD', '2021AA', 'Chemical Biology and Drug Development Vocabulary'),
        ('NCI_CDC', '2021AA', 'U.S. Centers for Disease Control and Prevention Terms'),
        ('NCI_CDISC', '2021AA', 'CDISC Terminology'),
        ('NCI_CDISC-GLOSS', '2021AA', 'CDISC Glossary Terminology'),
        ('NCI_CELLOSAURUS', '2021AA', 'Cellosaurus'),
        ('NCI_CRCH', '2021AA', 'Cancer Research Center of Hawaii Nutrition Terminology'),
        ('NCI_CTCAE', '2021AA', 'Common Terminology Criteria for Adverse Events 4.3 Subset'),
        ('NCI_CTCAE_3', '2021AA', 'Common Terminology Criteria for Adverse Events 3.0'),
        ('NCI_CTCAE_5', '2021AA', 'Common Terminology Criteria for Adverse Events 5.0'),
        ('NCI_CTDC', '2021AA', 'Clinical Trial Data Commons'),
        ('NCI_CTEP-SDC', '2021AA', 'Cancer Therapy Evaluation Program - Simple Disease Classification'),
        ('NCI_CTRP', '2021AA', 'Clinical Trials Reporting Program Terms'),
        ('NCI_DCP', '2021AA', 'NCI Division of Cancer Prevention Program Terms'),
        ('NCI_DICOM', '2021AA', 'Digital Imaging Communications in Medicine Terms'),
        ('NCI_DTP', '2021AA', 'NCI Developmental Therapeutics Program'),
        ('NCI_EDQM-HC', '2021AA', 'European Directorate for the Quality of Medicines & Healthcare Terms'),
        ('NCI_FDA', '2021AA', 'FDA Terminology'),
        ('NCI_GAIA', '2021AA', 'Global Alignment of Immunization Safety Assessment in Pregnancy Terms'),
        ('NCI_GDC', '2021AA', 'NCI Genomic Data Commons Terms'),
        ('NCI_GENC', '2021AA', 'Geopolitical Entities, Names, and Codes (GENC) Standard Edition 1'),
        ('NCI_ICDC', '2021AA', 'NCI Integrated Canine Data Commons Terms'),
        ('NCI_ICH', '2021AA', 'International Conference on Harmonization Terms'),
        ('NCI_INC', '2021AA', 'International Neonatal Consortium'),
        ('NCI_JAX', '2021AA', 'Jackson Laboratories Mouse Terminology, adapted for NCI use'),
        ('NCI_KEGG', '2021AA', 'KEGG Pathway Database Terms'),
        ('NCI_NCI-GLOSS', '2021AA', 'NCI Dictionary of Cancer Terms'),
        ('NCI_NCI-HGNC', '2021AA', 'NCI HUGO Gene Nomenclature'),
        ('NCI_NCI-HL7', '2021AA', 'NCI Health Level 7'),
        ('NCI_NCPDP', '2021AA', 'NCPDP Terminology'),
        ('NCI_NICHD', '2021AA', 'NICHD Terminology'),
        ('NCI_PCDC', '2021AA', 'Pediatric Cancer Data Commons'),
        ('NCI_PI-RADS', '2021AA', 'Prostate Imaging Reporting and Data System Terms'),
        ('NCI_PID', '2021AA', 'National Cancer Institute Nature Pathway Interaction Database Terms'),
        ('NCI_RENI', '2021AA', 'Registry Nomenclature Information System'),
        ('NCI_UCUM', '2021AA', 'Unified Code for Units of Measure'),
        ('NCI_ZFin', '2021AA', 'Zebrafish Model Organism Database Terms'),
        ('NCISEER', '2002AD', 'NCI SEER ICD Mappings'),
        ('NDDF', '2021AA', 'FDB MedKnowledge'),
        ('NEU', '2020AB', 'Neuronames Brain Hierarchy'),
        ('NIC', '2018AB', 'Nursing Interventions Classification'),
        ('NOC', '2018AB', 'Nursing Outcomes Classification'),
        ('NUCCHCPT', '2021AA', 'National Uniform Claim Committee - Health Care Provider Taxonomy'),
        ('OMIM', '2021AA', 'Online Mendelian Inheritance in Man'),
        ('OMS', '2007AC', 'Omaha System'),
        ('PCDS', '1999AA', 'Patient Care Data Set'),
        ('PDQ', '2019AA', 'Physician Data Query'),
        ('PNDS', '2018AB', 'Perioperative Nursing Data Set'),
        ('PPAC', '1999AA', 'Pharmacy Practice Activity Classification'),
        ('PSY', '2005AB', 'Psychological Index Terms'),
        ('QMR', '1998AA', 'Quick Medical Reference'),
        ('RAM', '2000AA', 'Clinical Concepts by R A Miller'),
        ('RCD', '2000AA', 'Read Codes'),
        ('RCDAE', '2000AA', 'Read Codes Am Engl'),
        ('RCDSA', '2000AA', 'Read Codes Am Synth'),
        ('RCDSY', '2000AA', 'Read Codes Synth'),
        ('RXNORM', '2021AA', 'RXNORM'),
        ('SCTSPA', '2021AA', 'SNOMED CT Spanish Edition'),
        ('SNM', '1991AA', 'SNOMED 1982'),
        ('SNMI', '1999AA', 'SNOMED Intl 1998'),
        ('SNOMEDCT_US', '2021AA', 'SNOMED CT, US Edition'),
        ('SNOMEDCT_VET', '2021AA', 'SNOMED CT, Veterinary Extension'),
        ('SOP', '2021AA', 'Source of Payment Typology'),
        ('SPN', '2004AA', 'Standard Product Nomenclature'),
        ('SRC', '1995AA', 'Source Terminology Names (UMLS)'),
        ('TKMT', '2011AB', 'Traditional Korean Medical Terms'),
        ('ULT', '1995AA', 'UltraSTAR'),
        ('UMD', '2021AA', 'UMDNS'),
        ('USP', '2021AA', 'USP Compendial Nomenclature'),
        ('USPMG', '2020AA', 'USP Model Guidelines'),
        ('UWDA', '2003AC', 'Digital Anatomist'),
        ('VANDF', '2021AA', 'National Drug File'),
        ('WHO', '1999AA', 'WHOART'),
        ('WHOFRE', '1999AA', 'WHOART French'),
        ('WHOGER', '1999AA', 'WHOART German'),
        ('WHOPOR', '1999AA', 'WHOART Portuguese'),
        ('WHOSPA', '1999AA', 'WHOART Spanish');