name: "tagged-release"

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./DataTier-APIs/Quarkus-APIs
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Build & test"
        run: mvn -B clean package --file pom.xml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: v3.0.1
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            DataTier-APIs/Quarkus-APIs/target/*.jar
