name: "tagged-release"

on:
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./DataTier-APIs/Quarkus-APIs
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
#       - name: Checkout source
#         uses: actions/checkout@v2
      - uses: octokit/request-action@v2.x
        id: get_latest_tag
        with:
          route: GET /repos/jayfray12/DataSynthesis-1/tags
          owner: jayfray12
          repo: DataSynthesis-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.get_latest_tag.outputs.data }}" >> tags.json
      - name: Extract tag name
        uses: sergeysova/jq-action@v2
        id: tag-name
        with:
          cmd: jq .[0].name tags.json -r
      - run: "echo Tag: ${{ steps.tag-name.outputs.data }}"
      - run: "echo Tag1: ${{ fromJson(steps.get_latest_tag.outputs.data).name }}"
#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: '11'
#           distribution: 'adopt'
#       - name: "Build & test"
#         run: mvn -B clean package -Dquarkus.package.type=uber-jar --file pom.xml

#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           automatic_release_tag: v3.0.1
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           prerelease: false
#           files: |
#             DataTier-APIs/Quarkus-APIs/target/*.jar
